### ISSUE TITLE
Naming?

### ISSUE THREAD

**Issue by sdwfrost** [alan-turing-institute/PDMP.jl#28]
Hi all,

As a new Turing fellow, I was looking at the ATI GitHub site, and saw you had a Julia package on inference in PDMPs. I'm glad to see there's interest in using Julia there; we've had a package for simulating PDMPs on Github for a while: [https://github.com/sdwfrost/PDMP.jl](https://github.com/sdwfrost/PDMP.jl); this is mainly to employ a simple change of variable approach as an alternative to thinning, so there isn't any overlap with our package and yours, but it would probably be good to talk about name clashing; we were just about to submit to METADATA, but have held off for now.

**Comment by tlienart** [comment]
Hey Simon, 

Not sure what's the best way to proceed. As far as I'm aware both packages are completely different. I guess that ours could be renamed to PDMPMC the issue is that afaik there's now two papers that have been submitted referring to this package naming so I need to contact these guys and change it this is not going to be overnight. 

Re METADATA, I was mildly interested in submitting this one too, I ended up not having the time to do it so as far as I'm concerned, feel free to register yours first, on our side I'll see whether people are happy with a name change and take it from there. 

Is that ok with you?

**Comment by sdwfrost** [comment]
Dear Thibaut,

I'm not sure either; neither package is 'all-encompassing' of PDMPs. Perhaps PDMPSimulation.jl and PDMPSamplers.jl might help to separate?

**Comment by tlienart** [comment]
yes. I've sent an email around and we're going to brainstorm a bit, I'll come back here when we have a suitable alternative name.

**Comment by sdwfrost** [comment]
Great. How often are you down at the ATI? Would be good to meet up.

**Comment by tlienart** [comment]
I'm not affiliated with the ATI anymore but I come occasionally on Tuesdays, happy to meet then

**Comment by tlienart** [comment]
we're converging towards `PDSampler.jl` it seems. so you're all clear for your METADATA update

btw, I've tried some other time to push on METADATA and found it rather unclear, if you find how to do it, could I bug you for a step-by-step explanation?

**Comment by sdwfrost** [comment]
Dear Thibaut,

The easiest way is to use [PkgDev.jl](https://github.com/JuliaLang/PkgDev.jl); tag and then publish. It can be a bit fiddly, but Tony Kelman always appears to be at hand to iron the wrinkles. I've made lots of idiotic mistakes in publishing [Gillespie.jl](https://github.com/sdwfrost/Gillespie.jl), so happy to help.

**Comment by tlienart** [comment]
Thanks Simon

Name now changing to PDSampler.jl, cheers.

**Comment by tlienart** [comment]
did this (suggested by tkelman)

```
Pkg.checkout("PDSampler")
Pkg.update()
import PkgDev
cd(Pkg.dir("METADATA"))
run(`git checkout -b tagpdsampler`)
PkgDev.tag("PDSampler")
run(`git remote add mine https://github.com/tlienart/METADATA.jl`)
run(`git push mine tagpdsampler`) # or from shell mode with ;
cd(Pkg.dir("PDSampler"))
run(`git remote add mine https://github.com/alan-turing-institute/PDSampler.jl`)
run(`git push mine --tags`) # or from shell mode with ;
```

and PR on METADATA, we'll see what happens :p
