### ISSUE TITLE
registering package

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/PDMP.jl#29]
It would be nice to register this package on METADATA.jl.

After several failed attempts, I'm giving up but if someone more savvy than I offers to help I'll be grateful. One difficulty is that the name of the package changed (PDMP->PDSampler). No idea how to go around this cleanly.

**Comment by vollmersj** [comment]
lets ask the julia folk on tuesday

**Comment by tlienart** [comment]
^ Asked and fixed... should be public in a day or so
